### ISSUE TITLE
DeserializationError: Deserialization error: Wrong directory fields

### ISSUE THREAD

**Issue by victor-lund** [JrCs/docker-letsencrypt-nginx-proxy-companion#125]
Hi there,

I have come across an error that I can't seem to solve. I successfully used the docker-letsencrypt-nginx-proxy-companion before, but now when i tried using it on a new server for one of my sub-domain, I get this error when trying the easiest setup:

`` DeserializationError: Deserialization error: Wrong directory fields``

Full log when running docker-compose logs:

```
letsencrypt-nginx-proxy-companion    | + local method=GET
letsencrypt-nginx-proxy-companion    | + [[ -n '' ]]
letsencrypt-nginx-proxy-companion    | + [[ -z unix:///var/run/docker.sock ]]
letsencrypt-nginx-proxy-companion    | + [[ unix:///var/run/docker.sock == unix://* ]]
letsencrypt-nginx-proxy-companion    | + curl_opts+=(--unix-socket ${DOCKER_HOST#unix://})
letsencrypt-nginx-proxy-companion    | + scheme=http:
letsencrypt-nginx-proxy-companion    | + [[ GET = \P\O\S\T ]]
letsencrypt-nginx-proxy-companion    | + curl -s --unix-socket /var/run/docker.sock -XGET http:/containers/6c377f2b4ad9/json
letsencrypt-nginx-proxy-companion    | + [[ 0 -ne 0 ]]
letsencrypt-nginx-proxy-companion    | + [[ ! -d /etc/nginx/certs ]]
letsencrypt-nginx-proxy-companion    | + touch /etc/nginx/certs/.check_writable
letsencrypt-nginx-proxy-companion    | + [[ 0 -ne 0 ]]
letsencrypt-nginx-proxy-companion    | + rm -f /etc/nginx/certs/.check_writable
letsencrypt-nginx-proxy-companion    | + check_writable_directory /etc/nginx/vhost.d
letsencrypt-nginx-proxy-companion    | + local dir=/etc/nginx/vhost.d
letsencrypt-nginx-proxy-companion    | + grep -q '^"/etc/nginx/vhost.d"$'
letsencrypt-nginx-proxy-companion    | + jq '.Mounts[].Destination'
letsencrypt-nginx-proxy-companion    | + docker_api /containers/6c377f2b4ad9/json
letsencrypt-nginx-proxy-companion    | + local scheme
letsencrypt-nginx-proxy-companion    | + curl_opts=(-s)
letsencrypt-nginx-proxy-companion    | + local curl_opts
letsencrypt-nginx-proxy-companion    | + local method=GET
letsencrypt-nginx-proxy-companion    | + [[ -n '' ]]
letsencrypt-nginx-proxy-companion    | + [[ -z unix:///var/run/docker.sock ]]
letsencrypt-nginx-proxy-companion    | + [[ unix:///var/run/docker.sock == unix://* ]]
letsencrypt-nginx-proxy-companion    | + curl_opts+=(--unix-socket ${DOCKER_HOST#unix://})
letsencrypt-nginx-proxy-companion    | + scheme=http:
letsencrypt-nginx-proxy-companion    | + [[ GET = \P\O\S\T ]]
letsencrypt-nginx-proxy-companion    | + curl -s --unix-socket /var/run/docker.sock -XGET http:/containers/6c377f2b4ad9/json
letsencrypt-nginx-proxy-companion    | + [[ 0 -ne 0 ]]
letsencrypt-nginx-proxy-companion    | + [[ ! -d /etc/nginx/vhost.d ]]
letsencrypt-nginx-proxy-companion    | + touch /etc/nginx/vhost.d/.check_writable
letsencrypt-nginx-proxy-companion    | + [[ 0 -ne 0 ]]
letsencrypt-nginx-proxy-companion    | + rm -f /etc/nginx/vhost.d/.check_writable
letsencrypt-nginx-proxy-companion    | + check_writable_directory /usr/share/nginx/html
letsencrypt-nginx-proxy-companion    | + local dir=/usr/share/nginx/html
letsencrypt-nginx-proxy-companion    | + grep -q '^"/usr/share/nginx/html"$'
letsencrypt-nginx-proxy-companion    | + jq '.Mounts[].Destination'
letsencrypt-nginx-proxy-companion    | + docker_api /containers/6c377f2b4ad9/json
letsencrypt-nginx-proxy-companion    | + local scheme
letsencrypt-nginx-proxy-companion    | + curl_opts=(-s)
letsencrypt-nginx-proxy-companion    | + local curl_opts
letsencrypt-nginx-proxy-companion    | + local method=GET
letsencrypt-nginx-proxy-companion    | + [[ -n '' ]]
letsencrypt-nginx-proxy-companion    | + [[ -z unix:///var/run/docker.sock ]]
letsencrypt-nginx-proxy-companion    | + [[ unix:///var/run/docker.sock == unix://* ]]
letsencrypt-nginx-proxy-companion    | + curl_opts+=(--unix-socket ${DOCKER_HOST#unix://})
letsencrypt-nginx-proxy-companion    | + scheme=http:
letsencrypt-nginx-proxy-companion    | + [[ GET = \P\O\S\T ]]
nginx-gen                            | 2016/11/24 11:03:53 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
nginx-gen                            | 2016/11/24 11:03:53 Sending container 'nginx' signal '1'
nginx-gen                            | 2016/11/24 11:03:53 Watching docker events
nginx-gen                            | 2016/11/24 11:03:53 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-gen                            | 2016/11/24 11:04:16 Received event start for container 96c8db026d9d
nginx-gen                            | 2016/11/24 11:04:21 Debounce minTimer fired
nginx-gen                            | 2016/11/24 11:04:21 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx-gen                            | 2016/11/24 11:04:21 Sending container 'nginx' signal '1'
nginx-gen                            | 2016/11/24 11:06:53 Received signal: hangup
nginx-gen                            | 2016/11/24 11:06:53 Received signal: hangup
nginx-gen                            | 2016/11/24 11:06:53 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx-gen                            | 2016/11/24 11:06:53 Sending container 'nginx' signal '1'
letsencrypt-nginx-proxy-companion    | + curl -s --unix-socket /var/run/docker.sock -XGET http:/containers/6c377f2b4ad9/json
letsencrypt-nginx-proxy-companion    | + [[ 0 -ne 0 ]]
letsencrypt-nginx-proxy-companion    | + [[ ! -d /usr/share/nginx/html ]]
letsencrypt-nginx-proxy-companion    | + touch /usr/share/nginx/html/.check_writable
letsencrypt-nginx-proxy-companion    | + [[ 0 -ne 0 ]]
letsencrypt-nginx-proxy-companion    | + rm -f /usr/share/nginx/html/.check_writable
letsencrypt-nginx-proxy-companion    | + check_dh_group
letsencrypt-nginx-proxy-companion    | + [[ ! -f /etc/nginx/certs/dhparam.pem ]]
letsencrypt-nginx-proxy-companion    | + echo 'Creating Diffie-Hellman group (can take several minutes...)'
letsencrypt-nginx-proxy-companion    | Creating Diffie-Hellman group (can take several minutes...)
letsencrypt-nginx-proxy-companion    | + openssl dhparam -out /etc/nginx/certs/.dhparam.pem.tmp 2048
letsencrypt-nginx-proxy-companion    | Generating DH parameters, 2048 bit long safe prime, generator 2
letsencrypt-nginx-proxy-companion    | This is going to take a long time


// generating code

letsencrypt-nginx-proxy-companion    | + mv /etc/nginx/certs/.dhparam.pem.tmp /etc/nginx/certs/dhparam.pem
letsencrypt-nginx-proxy-companion    | + exec /bin/bash /app/start.sh
letsencrypt-nginx-proxy-companion    | Sleep for 3600s
letsencrypt-nginx-proxy-companion    | 2016/11/24 11:06:53 Generated '/app/letsencrypt_service_data' from 2 containers
letsencrypt-nginx-proxy-companion    | 2016/11/24 11:06:53 Running '/app/update_certs'
letsencrypt-nginx-proxy-companion    | 2016/11/24 11:06:53 Watching docker events
letsencrypt-nginx-proxy-companion    | 2016/11/24 11:06:53 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
letsencrypt-nginx-proxy-companion    | Reloading nginx proxy (using separate container nginx-gen)...
letsencrypt-nginx-proxy-companion    | Creating/renewal mydomainname.com certificates... (mydomainname.com)
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:53,866:DEBUG:simp_le:1371: ['-f', 'account_key.json', '-f', 'key.pem', '-f', 'fullchain.pem', '-f', 'cert.pem', '--tos_sha256', '6373439b9f29d67a5cd4d18cbc7f264809342dbf21cb2ba2fc7588df987a6221', '-v', '-d', 'mydomainname.com', '--email', 'info@mydomainname.com', '--server=https://acme-staging.api.letsencrypt.org/directory', '--default_root', '/usr/share/nginx/html/'] parsed as Namespace(account_key_public_exponent=65537, account_key_size=4096, cert_key_size=4096, default_root='/usr/share/nginx/html/', email='info@mydomainname.com', help=False, integration_test=False, ioplugins=['account_key.json', 'key.pem', 'fullchain.pem', 'cert.pem'], reuse_key=False, revoke=False, server='https://acme-staging.api.letsencrypt.org/directory', test=False, tos_sha256='6373439b9f29d67a5cd4d18cbc7f264809342dbf21cb2ba2fc7588df987a6221', user_agent='simp_le/0', valid_min=2592000, verbose=True, version=False, vhosts=[Vhost(name='mydomainname.com', root=None)])
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:53,868:DEBUG:simp_le:367: Loading account_key.json
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:53,868:DEBUG:simp_le:367: Loading key.pem
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:53,869:DEBUG:simp_le:367: Loading fullchain.pem
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:53,869:DEBUG:simp_le:367: Loading cert.pem
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:53,869:DEBUG:simp_le:1280: Computed roots: {'mydomainname.com': '/usr/share/nginx/html/'}
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:53,869:INFO:simp_le:1211: Generating new account key
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:56,567:DEBUG:root:605: Sending GET request to https://acme-staging.api.letsencrypt.org/directory. args: (), kwargs: {}
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:56,572:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:56,796:DEBUG:requests.packages.urllib3.connectionpool:387: "GET /directory HTTP/1.1" 200 372
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:56,800:DEBUG:root:611: Received <Response [200]>. Headers: {'Content-Length': '372', 'Expires': 'Thu, 24 Nov 2016 11:06:56 GMT', 'Boulder-Request-Id': 'ymjee7KdqR_NeRxvyBQdAGYchtpXjwh5dLplrigc2BA', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 24 Nov 2016 11:06:56 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'hCMbh98MyZ_ZA5qVwEvSMAxrgBgtE-ivt7fIaId4zS8'}. Content: '{\n  "key-change": "https://acme-staging.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-staging.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-staging.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-staging.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-staging.api.letsencrypt.org/acme/revoke-cert"\n}'
letsencrypt-nginx-proxy-companion    | 2016-11-24 11:06:56,800:DEBUG:acme.client:551: Received response <Response [200]> (headers: {'Content-Length': '372', 'Expires': 'Thu, 24 Nov 2016 11:06:56 GMT', 'Boulder-Request-Id': 'ymjee7KdqR_NeRxvyBQdAGYchtpXjwh5dLplrigc2BA', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 24 Nov 2016 11:06:56 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'hCMbh98MyZ_ZA5qVwEvSMAxrgBgtE-ivt7fIaId4zS8'}): '{\n  "key-change": "https://acme-staging.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-staging.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-staging.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-staging.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-staging.api.letsencrypt.org/acme/revoke-cert"\n}'
letsencrypt-nginx-proxy-companion    | Traceback (most recent call last):
letsencrypt-nginx-proxy-companion    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
letsencrypt-nginx-proxy-companion    |     return main_with_exceptions(cli_args)
letsencrypt-nginx-proxy-companion    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
letsencrypt-nginx-proxy-companion    |     persist_new_data(args, existing_data)
letsencrypt-nginx-proxy-companion    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
letsencrypt-nginx-proxy-companion    |     client = registered_client(args, existing_data.account_key)
letsencrypt-nginx-proxy-companion    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
letsencrypt-nginx-proxy-companion    |     client = acme_client.Client(directory=args.server, key=key, net=net)
letsencrypt-nginx-proxy-companion    |   File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
letsencrypt-nginx-proxy-companion    |     self.net.get(directory).json())
letsencrypt-nginx-proxy-companion    |   File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
letsencrypt-nginx-proxy-companion    |     raise jose.DeserializationError(str(error))
letsencrypt-nginx-proxy-companion    | DeserializationError: Deserialization error: Wrong directory fields
letsencrypt-nginx-proxy-companion    | 
letsencrypt-nginx-proxy-companion    | Unhandled error has happened, traceback is above
letsencrypt-nginx-proxy-companion    | 
letsencrypt-nginx-proxy-companion    | Debugging tips: -v improves output verbosity. Help is available under --help.
letsencrypt-nginx-proxy-companion    | Sleep for 3600s
```

I tried this with the following setup:

**~/docker/_proxy/docker-compose.yml:**
```
version: "2"

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - DEBUG=true

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

**~/docker/test/docker-compose.yml:**
```
version: "2"

services:

  simple-site:
    image: nginx
    container_name: simple-site
    volumes:
      - "./site/conf.d/:/etc/nginx/conf.d"
      - "./site/site/:/var/www/html"
    environment:
      - VIRTUAL_HOST=mydomainname.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mydomainname.com
      - LETSENCRYPT_EMAIL=info@mydomainname.com
      - LETSENCRYPT_TEST=true
      - DEBUG=true
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy

```

**~/docker/test/site/conf.d/mydomainname.com.conf:**
```
server {
    listen                  80;
    server_name             mydomainname.com;
    root                    /var/www/html;
}
```

In my certs folder, an empty folder with the domain name _mydomainname.com_ is created but remains empty. nothing else is getting written to the certs folder..

Furthermore, accessing http://mydomainname.com works (html is printed) but using http**s**://mydomainname.com** gives me "mydomainname.com refused to connect."

I am assuming that I am missing something obvious - as i said, a similar setup worked for me before - but I can't get my head around what I've done wrong...

Anyone has any ideas?

**Comment by shageman** [comment]
@victor-lund I have been seeing the same error. Try it without LETSENCRYPT_TEST=true. For the the error seems to go away (I can't confirm that everything works because I am still having other issues with the setup).

**Comment by victor-lund** [comment]
@shageman A big thanks - I can confirm that the issue was indeed the "LETSENCRYPT_TEST" feature - it appears to be broken causing the failures I've been having.

**Comment by victor-lund** [comment]
@JrCs This should probably be labeled as a bug

**Comment by minadyn** [comment]
I'm having this issue too, and it looks like this is due to the simp_le client using an older version of the acme-python library.  In particular, the failure happens [here](https://github.com/certbot/certbot/blob/v0.5.0/acme/acme/messages.py#L140) where the api directory endpoint returns some directory fields that the acme-python library does not recognize.  

It looks like [this commit](https://github.com/certbot/certbot/commit/6f9e28fccad96c19b3fd58560d5c6ddba8201d04) fixes the issue with the acme-python library, so I think this can be fixed if the simp_le client uses acme 0.6.0 or greater.

**Comment by nathang21** [comment]
Can confirm after much troubleshooting, removing the test let everything
started working.

**Comment by ObjectiveTruth** [comment]
Is there a workaround for this? or ETA on fix?
