### ISSUE TITLE
renewals are not happening

### ISSUE THREAD

**Issue by tve** [JrCs/docker-letsencrypt-nginx-proxy-companion#146]
I have a couple of letsencrypt containers running, started in October. I'm now finding that they are not renewing the certs and my question is how to troubleshoot this. What I'm seeing in the container logs is:
```
Jan  9 09:40:14 idocs idocs_letsencrypt_1[691]: Creating/renewal idocs.example.com certificates... (idocs.example.com)
Jan  9 09:40:14 idocs idocs_letsencrypt_1[691]: Sleep for 3600s
```

But the certs aren't being renewed and run out in ~2 weeks. I did a docker exec into the container and I see:
```
/etc/nginx/certs/idocs.example.com:
total 16
     4 -rw-r--r--    1 root     root          3169 Jun 30  2016 account_key.json
     4 -rw-r--r--    1 root     root          2158 Oct 28 19:05 cert.pem
     4 -rw-r--r--    1 root     root          3805 Oct 28 19:05 fullchain.pem
     4 -rw-r--r--    1 root     root          3271 Oct 28 19:05 key.pem
```
So it looks like nothing has been updated. I don't see any errors anywhere. Where do I need to look to see what's going on?

**Comment by tve** [comment]
I now see that in one of the containers I see an error
```
Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
Sleep for 3600s
Creating/renewal xyz.example.com certificates... (xyz.example.com)
2017-01-09 18:16:28,877:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields
```

**Comment by tve** [comment]
FYI, I pulled the latest companion docker image and relaunched the companion container and that did a renewal. I'd still like to know how to tell what was going wrong.

**Comment by deadcyclo** [comment]
See issue #130
