### ISSUE TITLE
Bad handshake, unexpected EOF

### ISSUE THREAD

**Issue by awesomejerry** [JrCs/docker-letsencrypt-nginx-proxy-companion#179]
Can't create new certs and the verbose mode and DEBUG didn't help.

Is there anyone encountering this?

<img width="1125" alt="2017-03-02 23 21 45" src="https://cloud.githubusercontent.com/assets/6601073/23536588/e2c14d16-0000-11e7-9975-259e74de102e.png">

https://answers.atlassian.com/questions/32508806/sslerror-bad-handshake-syscallerror-1-unexpected-eof-when-creating-jira-object-on-python

https://community.letsencrypt.org/t/certbot-sslerror/28687

**Comment by nwallace** [comment]
I was maybe getting a similar error:

```
2017-03-09 04:38:21,763:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields
```

I had been running a slightly out-of-date version, though, so I updated my containers to the newest stable versions (v1.4 of this companion, alongside docker-gen 0.7.3 and nginx 1:11).  After updating my containers to newer versions, I'm getting this error:

```
Creating/renewal mydomain.example certificates... (mydomain.example)
2017-03-09 04:49:58,832:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-03-09 04:49:59,509:INFO:requests.packages.urllib3.connectionpool:242: Resetting dropped connection: acme-v01.api.letsencrypt.org
2017-03-09 04:49:59,879:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): mydomain.example
2017-03-09 04:49:59,940:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): mydomain.example
2017-03-09 04:50:00,119:ERROR:acme.challenges:256: Unable to reach http://mydomain.example/.well-known/acme-challenge/BIGLONGCHALLENGESTRING: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
2017-03-09 04:50:00,120:WARNING:simp_le:1303: mydomain.example was not successfully self-verified. CA is likely to fail as well!
2017-03-09 04:50:00,312:INFO:simp_le:1313: Generating new certificate private key
2017-03-09 04:50:03,618:ERROR:simp_le:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/BIGLONGAUTHSTRING
```
