### ISSUE TITLE
Certificates are not renewed

### ISSUE THREAD

**Issue by nicolinux** [JrCs/docker-letsencrypt-nginx-proxy-companion#184]
Hi,

I just realized that the letsencrypt certs are not renewed. If I look at the proxy-companion container, I see the following output:
```
Creating/renewal spielhaus-ftw.com certificates... (spielhaus-ftw.com www.spielhaus-ftw.com)
2017-03-11 12:27:35,571:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
Sleep for 3600s
2017/03/11 12:30:19 Received event die for container 7f46c2e70c40
2017/03/11 12:30:34 Debounce minTimer fired
2017/03/11 12:30:34 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
2017/03/11 12:32:49 Received event start for container 7f46c2e70c40
2017/03/11 12:33:04 Debounce minTimer fired
2017/03/11 12:33:04 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
```

Any idea what is up with this?
I didn't update the proxy-companion image, so it might be a known bug - sorry if it is.

**Comment by matt-hh** [comment]
An update to the latest image should fix this issue.

**Comment by nicolinux** [comment]
That's true, the issue has been solved. Thanks!
