### ISSUE TITLE
DeserializationError again

### ISSUE THREAD

**Issue by ikarulus** [JrCs/docker-letsencrypt-nginx-proxy-companion#305]
This one is not new (#130), should already be fixed. I'm getting this anyway.
```
nginx-gen            | 2017/12/18 14:15:59 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx-gen            | 2017/12/18 14:15:59 Sending container 'nginx-web' signal '1'
nginx-letsencrypt    | 2017-12-18 14:15:59,938:INFO:simp_le:1211: Generating new account key
nginx-letsencrypt    | 2017-12-18 14:16:00,470:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
nginx-letsencrypt    | Traceback (most recent call last):
nginx-letsencrypt    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
nginx-letsencrypt    |     return main_with_exceptions(cli_args)
nginx-letsencrypt    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
nginx-letsencrypt    |     persist_new_data(args, existing_data)
nginx-letsencrypt    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
nginx-letsencrypt    |     client = registered_client(args, existing_data.account_key)
nginx-letsencrypt    |   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
nginx-letsencrypt    |     client = acme_client.Client(directory=args.server, key=key, net=net)
nginx-letsencrypt    |   File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
nginx-letsencrypt    |     self.net.get(directory).json())
nginx-letsencrypt    |   File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
nginx-letsencrypt    |     raise jose.DeserializationError(str(error))
nginx-letsencrypt    | DeserializationError: Deserialization error: Wrong directory fields
nginx-letsencrypt    | 
nginx-letsencrypt    | Unhandled error has happened, traceback is above
```
I'm using this setup https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
Also getting this error using similar, own setups.

**Comment by buchdag** [comment]
You are using an outdated version of the container, please try pulling `stable` / `v1.6` or `latest`

**Comment by ikarulus** [comment]
Works for me, thanks.

**Comment by donicrosby** [comment]
@buchdag I'm running both containers on armhf does anyone have a docker repo that works for armhf that uses the most recent version of both containers?

**Comment by buchdag** [comment]
@donicrosby I'm afraid I won't be of much help, neither this project nor nginx-proxy officially supports archs others than `amd64`.

But alpine and nginx are now both natively multiarch, and `jwilder/docker-gen` provides binary for `armhf` so I think it's totally doable to create armhf Dockerfiles for both with a bit of tinkering and build them on you `armhf` device.

Out of curiosity, were did you get your current `armhf` images from ?
