### ISSUE TITLE
HTTPS is rejected but HTTP works

### ISSUE THREAD

**Issue by donicrosby** [JrCs/docker-letsencrypt-nginx-proxy-companion#306]
I am having and issue with getting certificates to work I can access http it works but when I use https I have an error "connection refused".

This is the error I get in the companion's logs

```
2017-12-19 19:09:50,613:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le-0-py2.7.egg/simp_le.py", line 1390, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le-0-py2.7.egg/simp_le.py", line 1375, in main_with_exceptions
    new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le-0-py2.7.egg/simp_le.py", line 1271, in new_data
    client = registered_client(args, existing.account_key)
  File "/usr/lib/python2.7/site-packages/simp_le-0-py2.7.egg/simp_le.py", line 1215, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "/usr/lib/python2.7/site-packages/acme-0.1.0-py2.7.egg/acme/client.py", line 60, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/site-packages/acme-0.1.0-py2.7.egg/acme/messages.py", line 164, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields
```

I'm not sure if it's an issue with nginx-proxy or the companion as the port is open but no traffic can get through.

**Comment by buchdag** [comment]
Please see #305
