### ISSUE TITLE
Redirect to www subdomain

### ISSUE THREAD

**Issue by brandon-welsch** [JrCs/docker-letsencrypt-nginx-proxy-companion#345]
Hey, can I set up the container somehow to always redirect all requests to www ?

Example :
- domain.com => www.domain.com

**Comment by buchdag** [comment]
This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different people.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)

**Comment by FallenRiteMonk** [comment]
@buchdag I have the same situation (at least almost, i redirect the other way around), but i get an error with the certificate generation.

My setup is the following:
I use jwilders proxy-gen (seperate container not the nginx-proxy)
the proxy-gen is setup to have the redirects from www.<MY_DOMAIN>.com to <MY_DOMAIN>.to (also listenings on 443 so https://www.<MY_DOMAIN>.com should also be redirected to https://<MY_DOMAIN>.com)
I have a container with VIRTUAL_HOST <MY_DOMAIN>.com and LETSENCYPT_HOST <MY_DOMAIN>.com,www.<MY_DOMAIN>.com

the problem is that this companion ist able to generate the cert anymore, even though <MY_DOMAIN>.com and www.<MY_DOMAIN>.com are reachable, but www.<MY_DOMAIN>.com returns a 301 redirect to <MY_DOMAIN>.com.
The error thrown is the following:
```
Creating/renewal <MY_DOMAIN>.com certificates... (<MY_DOMAIN>.com www.<MY_DOMAIN>.com)
/usr/lib/python2.7/site-packages/acme/jose/jwa.py:110: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(self.padding, self.hash)
2018-05-14 08:20:21,166:INFO:simp_le:1479: Generating new certificate private key
2018-05-14 08:20:23,602:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/Qi_5SbKefTI2XvOqtF_ab5ZKGuF_6yClVYzBvFD8VqI
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1489, in persist_new_data
    account_key=client.key, key=None, cert=None, chain=None))
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1195, in persist_data
    plugin.save(new_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 493, in save
    key = self.dump_key(data.key)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 436, in dump_key
    return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()
AttributeError: 'NoneType' object has no attribute 'wrapped'

Unhandled error has happened, traceback is above
```

any ideas on what could be the problem? or ideas how i could get it to work?
