### ISSUE TITLE
Missing intermediate certificates

### ISSUE THREAD

**Issue by jpic** [JrCs/docker-letsencrypt-nginx-proxy-companion#457]
Hi all,

Apparently, nginx doesn't serve intermediary certificates. Resulting, for example, in:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/usr/lib/python3.6/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python3.6/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
['This is a test message generated using ``raven test``']

```

Can we change the default configuration so that we add them ?

**Comment by buchdag** [comment]
Could you be a bit more specific about how you ended up with this error ?

FIY using somewhat recent versions (as in less than 12-18 months old) of both this container and `nginx-proxy` (or the `nginx.tmpl` file), the intermediate is correctly included.

**Comment by jpic** [comment]
Sure, this is our exact setup as an [ansible tasks file](https://yourlabs.io/oss/playlabs/blob/master/playlabs/roles/nginx/tasks/main.yml)

We have an instance of sentry behind it, with [again ansible task file](https://yourlabs.io/oss/playlabs/blob/master/playlabs/roles/sentry/tasks/main.yml)

Finally, I get this error when trying to open the url to sentry through python, which requires intermediate certificates from what I've read on internet because it doesn't seem able to use server-wide certificates ?

**Comment by jpic** [comment]
I have news, it works for me on openssl 1.1.1 Sept 2018 but not 1.0.2p Aug 2018:

```
bash-4.4# openssl version         
OpenSSL 1.0.2p  14 Aug 2018       


bash-4.4# openssl s_client -showcerts -connect sentry.mrs.beta.gouv.fr:443                                                               
CONNECTED(00000003)               
depth=0 CN = letsencrypt-nginx-proxy-companion                      
verify error:num=18:self signed certificate                         
verify return:1                   
depth=0 CN = letsencrypt-nginx-proxy-companion                      
verify return:1                   
---                               
Certificate chain                 
 0 s:/CN=letsencrypt-nginx-proxy-companion                          
   i:/CN=letsencrypt-nginx-proxy-companion                          
-----BEGIN CERTIFICATE-----       
MIIE1DCCArwCCQDOVMI6jl30cTANBgkqhkiG9w0BAQsFADAsMSowKAYDVQQDDCFs    
ZXRzZW5jcnlwdC1uZ2lueC1wcm94eS1jb21wYW5pb24wHhcNMTgxMDEwMTcyNjM1    
WhcNMTkxMDEwMTcyNjM1WjAsMSowKAYDVQQDDCFsZXRzZW5jcnlwdC1uZ2lueC1w    
cm94eS1jb21wYW5pb24wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCr    
QsJ7FSyNFjPf3XBmCy+TRCzWnVmD6OxwUkOq75dcPBFcQ7/m7kmZbE/oYoX6rOAh    
Ws2qxthCX2kzxtb79HCd7G7VQEglKO8tQT1HQMXSWghc+ZpufnVEfrGEunJt1GbG    
eNMqNVKnHd2sLtHCxzbJsLRl6jQ0FccFn/5Aeuj7t4nsX6bZDe35wML4rngc0Ymb    
KRPSO8WAKN7RWtisWZvyetl+KerfH5foJxO2DD1qw9DMAkMy/6WCYMqBVsVj3SvG    
sTPQ7b5K4lI2w5MVGAgUvUTBuWaX+AXU87UY/5WJR/vuB3xQk3czZMmA/GjBRQSq    
r4bTVB8LTKjDHTzQEuMQRXiDNcvAdi5ztdl0k8ZLmtE8CPu0csGTI1hX9JBOozrD    
Y0woO3E9kV1pRi6g19Z6l/gRK3Z8JWIg3JsA1618U1CKwHNgl4g6to1XdEfjLQKj    
dv/ckThGuExJumaGZHrSdW8XdPwntmu6b5uLBAbfFmn7j9Zq4OZgQg+WVUKZsvS4    
sQQBLKTa2Q/IU4mVkB10c/ickKV59j+Utbf4huw/ouW34WYwAiRwnSfLMqDILTKT    
GHK6Re9nJtqnByetZ5pw1V5bpnp8SqYqaIvTJ1L3p1YEHyVeKJMDi6dGsnfRD260    
ZhEjmg9F6wXBVqgKl416z0hBtLRyqmn+LKACQAlzFwIDAQABMA0GCSqGSIb3DQEB    
CwUAA4ICAQBbic0GaRF86pGO3EzSKaXxTXG3EjVwCIOpzoDX4tayGlykMkjFkXSJ    
K/NdVwTK2w7azwWOKeKfO657bjGxi0OqA5e5EpAPHcY3QDSNF3ahENRCC6URmMU6    
vwH9Fhkb/VldJCDejc8pJ6m9Toh9rrsxpK+/hgXamPnpks/HYK1p/LXIN/ZD8ro4    
Gb2glbEQ96Gp9dDXSJOI3ZQoFtuPMj/OiwQNYcHsp3Mhq+Qv+aD33f/1lOILktC/    
W4iDZasRwJVXwa9HvjikMPGz+oFQ+JDxXRWpRovdoS70NVhG8504qtv/Rrx5EYZr    
KPw0GKb4BnlxIWZ486UTh++cCzJq73wExocXTohe9qLOn26OCKB9jlBJC+12ObCt    
27vU8qw5ZBq/FydheQJFX8e+HttbnYTRu89Kz/6dEFCgL1Hp4lqthf0Uz5pfyiCS    
HPk13qRNrh3nJ4E6O2T89wwPPpX3V91j7FY6RcgfhR1DiQIGFpKaQphy7imIihAZ    
9O9KJZRMcU0RtzFgm9TzoiG3kUOHpAM7KKUgNo1JNXTM1JmPbHwuY0Vn6NBslhS9    
RROCn/6myKdLRdCtCeB1vqMVeXfkIC3nvvAF+85BKkmWg9XlWqy9WK7Tq5rMWqE+    
zFgC3vyujuTaohtVL2rxjoseHl2OTOP0Q9vWHEXHuOzb1Oo1bQDYhQ==            
-----END CERTIFICATE-----         
---                               
Server certificate                
subject=/CN=letsencrypt-nginx-proxy-companion                       
issuer=/CN=letsencrypt-nginx-proxy-companion                        
---                               
No client certificate CA names sent                                 
Peer signing digest: SHA512       
Server Temp Key: ECDH, P-256, 256 bits                              
---                               
SSL handshake has read 2008 bytes and written 433 bytes             
---                               
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384             
Server public key is 4096 bit     
Secure Renegotiation IS supported 
Compression: NONE                 
Expansion: NONE                   
No ALPN negotiated                
SSL-Session:                      
    Protocol  : TLSv1.2           
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384                         
    Session-ID: ADD1A0D21962B8BFE7FD467F1C4B230F636B75CB4F09A21C5EDD80E210E9B84C                                                         
    Session-ID-ctx:               
    Master-Key: 7277686D0554143FCF78FD748B06980373963F1982E8BE54D6DC3EA73BE2005E8F3E8FF115CF842ED7B67AACD540EB97                         
    Key-Arg   : None              
    PSK identity: None            
    PSK identity hint: None       
    SRP username: None            
    Start Time: 1539796452        
    Timeout   : 300 (sec)         
    Verify return code: 18 (self signed certificate)                
---                               
bash-4.4# getent hosts sentry.mrs.beta.gouv.fr
188.165.252.150   prod.mrs.beta.gouv.fr  prod.mrs.beta.gouv.fr sentry.mrs.beta.gouv.fr


now on openssl 1.1.1


17/10 2018 19:06:21 jpic@jpic ~/work/betagouv/inventory  (master)
$ getent hosts sentry.mrs.beta.gouv.fr
188.165.252.150 prod.mrs.beta.gouv.fr sentry.mrs.beta.gouv.fr

17/10 2018 19:06:22 jpic@jpic ~/work/betagouv/inventory  (master)
$ openssl s_client -showcerts -connect sentry.mrs.beta.gouv.fr:443
CONNECTED(00000005)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = sentry.mrs.beta.gouv.fr
verify return:1
---
Certificate chain
 0 s:CN = sentry.mrs.beta.gouv.fr
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
MIIHGTCCBgGgAwIBAgISA80FF3TegANLq186oMcpGYfyMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODEwMTcxNTU1NTBaFw0x
OTAxMTUxNTU1NTBaMCIxIDAeBgNVBAMTF3NlbnRyeS5tcnMuYmV0YS5nb3V2LmZy
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3mdB5MIaiQsuSFIpUodU
pAUJz+gDUHsc/ZDngOIaH7KVp7PAvLC2NxWezmPSW+Z5RJXzGTkVVaK/YJPIG6vh
HO32vZSFGtn/te2GOnOMo3kAdqtoPE6Co7lIe/aN69SRJH/COM4W8tBIQSQeTzX3
DNTCY/6/YHScmqu12Rrt+BPpaQXrN/4ig6ItOCOaY8//+VWAMXzr9P+Q/PD7bl0T
VIo6kWynGDHZ73K9MtAAxfkM9tm1gFiIHVaUpxI+3Ff5tlrsdIg3ZLz2PecOKto9
pI/RPxfBjqhjigzyueP5rkrVqFLDB3wQLKjblTSuI9O4iGLFBmG914oZEUT1hjJx
CQF+OX0ENPhYnN/RjM08QDr9zG5VwSv5AIUm1yeDZN3kyXaWEwaql2ZrTWIF4i2o
XQL3+tFmawhPwePsz7SI96R2vJ4oxQgniF4p3lA9FlMcUyXAgUjYm6wsxRfJJ6lS
ofZSRHvf7x4v/hj17bkUbpD66KyR/7LZ+Om2pEVbmpElUJ8Di6VerPnvJa/3EK5M
y+oGi2mNJYHO4su2XmGAqQVjl/xTv0Wo0HSEknx2pUzTKVty9uehLeWNUlLAXeYd
Jz2RbGz4LNUPZmlSvWNUGZ9Hf9yoC3IcO63qQ7EO+YxeuYXDfs9Vqu2IQh1PsYIc
nDHasy0KoB9rLLULDQyV5TECAwEAAaOCAx8wggMbMA4GA1UdDwEB/wQEAwIFoDAd
BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNV
HQ4EFgQUSJszKFyqH3bsTjXpomzNgPvwq2swHwYDVR0jBBgwFoAUqEpqYwR93brm
0Tm3pkVl7/Oo7KEwbwYIKwYBBQUHAQEEYzBhMC4GCCsGAQUFBzABhiJodHRwOi8v
b2NzcC5pbnQteDMubGV0c2VuY3J5cHQub3JnMC8GCCsGAQUFBzAChiNodHRwOi8v
Y2VydC5pbnQteDMubGV0c2VuY3J5cHQub3JnLzAiBgNVHREEGzAZghdzZW50cnku
bXJzLmJldGEuZ291di5mcjCB/gYDVR0gBIH2MIHzMAgGBmeBDAECATCB5gYLKwYB
BAGC3xMBAQEwgdYwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQu
b3JnMIGrBggrBgEFBQcCAjCBngyBm1RoaXMgQ2VydGlmaWNhdGUgbWF5IG9ubHkg
YmUgcmVsaWVkIHVwb24gYnkgUmVseWluZyBQYXJ0aWVzIGFuZCBvbmx5IGluIGFj
Y29yZGFuY2Ugd2l0aCB0aGUgQ2VydGlmaWNhdGUgUG9saWN5IGZvdW5kIGF0IGh0
dHBzOi8vbGV0c2VuY3J5cHQub3JnL3JlcG9zaXRvcnkvMIIBBAYKKwYBBAHWeQIE
AgSB9QSB8gDwAHcAdH7agzGtMxCRIZzOJU9CcMK//V5CIAjGNzV55hB7zFYAAAFm
gvR1ygAABAMASDBGAiEA+qAcA9gRL1qDvychkCo/KfFZiN0WDN130GA/9xCzehAC
IQC6SMdtNu1TysBl6oBRgZP4BWxF+sIQnGUuHuLhZQdNTQB1ACk8UZZUyDlluqpQ
/FgH1Ldvv1h6KXLcpMMM9OVFR/R4AAABZoL0d8UAAAQDAEYwRAIgIjHcSVVfkNOA
pZsMoLh23sRe4EYSljRb1So5tmxGxx8CIFCju9tUYThK/Z/8FzC2XjQWeQbD7ODU
XYp+MAa+X10dMA0GCSqGSIb3DQEBCwUAA4IBAQBZZfk3x3WaZljR67JnC14Kcd4L
ic2FabWEOMWB3OP8pmM+W4KT0CSt44zF91es14nbYcaskzRQqdfUHzXx0x1B6zjV
sqo2nQhdFQHhhfJzI4y/xh8BMN5mUvvQ9L9XorgYQI2ubwGtFd1wHkbO8CCghv88
wOpRGwk4vPZIpKJ3n/LcLvK2IySXFojmwmmy3yLXLc5X8DN3c63X02mYYCA3U8iX
qnjlSdSAc+IzTScKBUbFrCTH1T0Pjr7FVBPsdbS3gTyBRyLgCmapmEYwO9iE36xH
YwI4zeuYNvL5A+xwdzvZO/bSxmgjNk4BQxEMG1FIp7qkXTo00DDaqOv13TeO
-----END CERTIFICATE-----
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
---
Server certificate
subject=CN = sentry.mrs.beta.gouv.fr

issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

---
No client certificate CA names sent
Peer signing digest: SHA512
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3765 bytes and written 451 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 923BABB6C0259D469EB75592941D96C240C5E4F3457121988537AF0E45575A13
    Session-ID-ctx: 
    Master-Key: FF66151EF9F6FD43378E841C1720B2016374DEA80165ED68191067F0AECBEF759146C33A5EC46B6DC37E1972987BB558
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1539796000
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
closed

$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```

**Comment by jpic** [comment]
```
19:30    alanhuang  : is_null: it would appear that sending the Server Name Indication TLS extension has been 
                      the default in openssl since 1.1.1 
https://github.com/openssl/openssl/commit/481afe2ad1325caf4beb0b9dee89cf69e7825e99#diff-62a6896b0a930b81e6b85be1580819f3R164
19:31    alanhuang  : and if the SNI extension isn't sent, the server replies with the self-signed cert 
                      (nginx's default_server block is used to process the incoming TLS connection)
19:31    alanhuang  : at least, I'm assuming it's nginx, but that's not strictly relevant
```

**Comment by buchdag** [comment]
Yep, client SNI support is required to have working TLS with nginx-proxy.

If your client don't send the SNI it will receive the default certificate from nginx-proxy, and if you don't provide your own default certificate you'll get a self signed one created by the LE companion container (the one with `subject=/CN=letsencrypt-nginx-proxy-companion`).

Is there still an issue or can we close ?

**Comment by jpic** [comment]
I think this can close because I find no action to take here. We need to be patient until the internet upgrades :joy:

Thanks a heap for your feedback !

Have a beautiful day
