### ISSUE TITLE
renewal for long running containers?

### ISSUE THREAD

**Issue by perler** [JrCs/docker-letsencrypt-nginx-proxy-companion#503]
Is there an automatic renewal process in place for containers that run longer than 45 days? I start getting renewal messages from letsencrypt that the certificate is running out in 16 days and I wonder if I need to restart the container?

**Comment by Greek64** [comment]
Yes, `docker-letsencrypt-nginx-proxy-companion` should renew all certificates that are about to expire in less than 30 days, independent of the container runtime.
Do note, that you will get expiry notification mails for ALL created certificates, even those that you are currently not using.
Since `docker-letsencrypt-nginx-proxy-companion` removes the certificates if the respectable container (for which the certificates are meant) is not running, and recreates them at container start, you may very well be seeing these mails about certificates that you are not using anymore.

To check when your currently used certificates will expire, execute `docker exec nginx-letsencrypt /app/cert_status` (assuming `nginx-letsencrypt` is the name of the letsencrypt companion container).
If they will expire in less than 30 days, something went wrong with the auto-renewal process. If not, you can safely ignore the mails.

**Comment by buchdag** [comment]
What version of the container are you running ? Can you post the log output from the letsencrypt companion container (not the whole log, just the last execution of the loop) ?

**Comment by perler** [comment]
the container throws errors (see below), here the image inspect:
```
[
    {
        "Id": "sha256:274e964f3005d5a002a8caa518ae5a34421b112bddd907212d7427a87637de95",
        "RepoTags": [
            "jrcs/letsencrypt-nginx-proxy-companion:latest"
        ],
        "RepoDigests": [
            "jrcs/letsencrypt-nginx-proxy-companion@sha256:409c4da77ba683bcb1e5b60e30176ab337e158fefcd52aa1197483eb5eb3af38"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-12-26T14:01:01.45431757Z",
        "Container": "0edc01af38ed9b60bd4d2070a4e3668b4651ea8a6129ef9b4986992d070ffb07",
        "ContainerConfig": {
            "Hostname": "0edc01af38ed",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBUG=false",
                "DOCKER_HOST=unix:///var/run/docker.sock"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/bash\" \"/app/start.sh\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:bf9042ca9358c248259c233ded9c8054f00a3521f5e727a5e999e50983095d56",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "/bin/bash",
                "/app/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Yves Blusseau <90z7oey02@sneakemail.com> (@blusseau)"
            }
        },
        "DockerVersion": "18.03.1-ee-3",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBUG=false",
                "DOCKER_HOST=unix:///var/run/docker.sock"
            ],
            "Cmd": [
                "/bin/bash",
                "/app/start.sh"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:bf9042ca9358c248259c233ded9c8054f00a3521f5e727a5e999e50983095d56",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "/bin/bash",
                "/app/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Yves Blusseau <90z7oey02@sneakemail.com> (@blusseau)"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 85525482,
        "VirtualSize": 85525482,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/0deb0c8a9be7875f6c1953bdbae30bdeab154307280fb010c5159edd29289494/diff:/var/lib/docker/overlay2/896f9c886fa1a3416c1664a3e2943edd5b63119d82ff894a387f2980b0cd992f/diff:/var/lib/docker/overlay2/9a07e798f54cfefdaaaa326c3ed59eee2f0398f3706792f11e2ab5a7e56feffe/diff:/var/lib/docker/overlay2/5b01f0b4f61dd28cfebee18425aedaa1830b95e428b120d74ab8e5b9a9c00d44/diff:/var/lib/docker/overlay2/b1c720dc759b87b28a9e258546e2bbf5a736dc2744d460d7b910b82a22f519c5/diff",
                "MergedDir": "/var/lib/docker/overlay2/9cdb9440ae61084d78ab34c8bd573f1184371162888e2dcbc955fcac07093488/merged",
                "UpperDir": "/var/lib/docker/overlay2/9cdb9440ae61084d78ab34c8bd573f1184371162888e2dcbc955fcac07093488/diff",
                "WorkDir": "/var/lib/docker/overlay2/9cdb9440ae61084d78ab34c8bd573f1184371162888e2dcbc955fcac07093488/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:7bff100f35cb359a368537bb07829b055fe8e0b1cb01085a3a628ae9c187c7b8",
                "sha256:99480cd1562eddb7cc21fb7b645eaf09f5287a893993c317c20485ad8dc97209",
                "sha256:c4603763853602d2f27b5c21509912ce4876be1ed18532d59598ff0fc193762e",
                "sha256:88026ec711143b5c455b69512c35b1940bd0b979d0ef7a354257cffafe00cdeb",
                "sha256:f1079a7e4faa430c2eadc959c11bed0be12cef9904bce0b6305af0c34d4b558e",
                "sha256:4b5b5f608d8f85bdac720af287c4d7c79c2f7b8041ff1584e06efeb4bdc04ab0"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

```
```
/app

/etc/nginx/certs/subdomain.domain.com /app

Creating/renewal subdomain.domain.com certificates... (subdomain.domain.com)

2019-02-04 14:31:32,480:INFO:simp_le:1479: Generating new certificate private key

2019-02-04 14:31:39,792:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/vYnvdBWg8n5KPw-7X7m2UVlc3kVzQhtqWyK-EPDjgig

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main

    return main_with_exceptions(cli_args)

  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions

    persist_new_data(args, existing_data)

  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1489, in persist_new_data

    account_key=client.key, key=None, cert=None, chain=None))

  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1195, in persist_data

    plugin.save(new_data)

  File "/usr/lib/python2.7/site-packages/simp_le.py", line 493, in save

    key = self.dump_key(data.key)

  File "/usr/lib/python2.7/site-packages/simp_le.py", line 436, in dump_key

    return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()

AttributeError: 'NoneType' object has no attribute 'wrapped'


Unhandled error has happened, traceback is above


Debugging tips: -v improves output verbosity. Help is available under --help.

/app

Sleep for 3600s
```

**Comment by buchdag** [comment]
The container correctly attempts to renew the certificate but you are hitting an [authorization issue](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md).

**Comment by perler** [comment]
ok, thanks. I worked the list down and this seems to have been the issue:

> you are using an outdated version of either letsencrypt-nginx-proxy-companion or the nginx.tmpl file (if running a 3 containers setup)
> Pull jrcs/letsencrypt-nginx-proxy-companion:latest again and get the latest latest nginx.tmpl.

I pulled the latest container, but had to remove it and recreate it before it worked. a simple recreate (from portainer) didn't do the trick.
