### ISSUE TITLE
Connection Error when trying to renew

### ISSUE THREAD

**Issue by falcon15500** [JrCs/docker-letsencrypt-nginx-proxy-companion#52]
Has been working well for a couple of months now, but today was the first time to renew my certificates.  Checking the logs and I see this:

2016-04-19 01:31:31,463:INFO:simp_le:1372: Certificates already exist and renewal is not necessary, exiting with status code 1.
Sleep for 3600s
Creating/renewal nine-hells.net certificates... (nine-hells.net couch.nine-hells.net deluge.nine-hells.net ebooks.nine-hells.net plex.nine-hells.net plexconnect.nine-hells.net sabnzbd.nine-hells.net sickrage.nine-hells.net www.nine-hells.net zm.nine-hells.net)
2016-04-19 02:31:31,871:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-19 02:31:32,937:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-19 02:31:34,010:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1390, in main
    return main_with_exceptions(cli_args)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1375, in main_with_exceptions
    new_data(args, existing_data)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1271, in new_data
    client = registered_client(args, existing.account_key)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1221, in registered_client
    regr = client.register(new_reg)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 97, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 632, in post
    response = self._send_request('POST', url, data=data, **kwargs)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 591, in _send_request
    response = requests.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /acme/new-reg (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f065c0110>: Failed to establish a new connection: [Errno -3] Try again',))

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
Sleep for 3600s

As you can see, the initial attempt was before the renewal was required.  Next attempt an hour later and a problem arises.  It has done the same thing each hour since then.  Apart from deleting the certs and restarting (to re-create) - any ideas on what is going wrong?

M.

**Comment by JrCs** [comment]
It seems it can't connect to the acme server of letsencrypt.org.
Check that the dns and connections to internet are good.
Also double check the ACME_CA_URI variable if you have change it.
