### ISSUE TITLE
No such file or directory: 'account_key.json'

### ISSUE THREAD

**Issue by Magi1053** [JrCs/docker-letsencrypt-nginx-proxy-companion#522]
```
INFO:simp_le:1382: Generating new account key
INFO:simp_le:1407: By using simp_le, you implicitly agree to the CA's terms of service: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
INFO:simp_le:1479: Generating new certificate private key
INFO:simp_le:360: Saving account_key.json
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1486, in persist_new_data
    cert=certr.body, chain=client.fetch_chain(certr)))
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1195, in persist_data
    plugin.save(new_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 473, in save
    return self.save_to_file(key)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 362, in save_to_file
    with open(self.path, self.WRITE_MODE) as persist_file:
IOError: [Errno 2] No such file or directory: 'account_key.json'
```

**Comment by Magi1053** [comment]
I believe the issue comes from the file/directory `accounts/acme-v01.api.letsencrypt.org/directory/default.json` not existing. Even though the container has access to read and write as evident from certificates being created, for some reason the default.json is not being created.

**Comment by buchdag** [comment]
Hi.

Could you post more details about this issue ? Config, container's version, etc

**Comment by buchdag** [comment]
No updates from the issue's creator in 60 days, closing.
