### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'wrapped'

### ISSUE THREAD

**Issue by CWempe** [JrCs/docker-letsencrypt-nginx-proxy-companion#526]
My certificated cannot be renewed.
I know this error is mentioned in some issues already but I could not find a solution for my case.

I get this error log:

`docker logs -f nginx-letsencrypt`

```
/etc/nginx/certs/sub1.mydomain.com/app
Creating/renewal sub1.mydomain.com certificates... (sub1.mydomain.com)
2019-03-22 22:04:27,468:INFO:simp_le:1479: Generating new certificate private key
2019-03-22 22:04:32,068:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/RIM8F_FTa_PbYIWQLu9mRFsqK*******bTGhIiE
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1583, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1489, in persist_new_data
    account_key=client.key, key=None, cert=None, chain=None))
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1195, in persist_data
    plugin.save(new_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 493, in save
    key = self.dump_key(data.key)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 436, in dump_key
    return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()
AttributeError: 'NoneType' object has no attribute 'wrapped'

Unhandled error has happened, traceback is above
```

It worked for about a year without problem.
I guess an update of my nginx container broke it.
But I am not sure and it could be an update that is a few month old.

My domains are available via ddns via IPv4 and IPv6.
But IPv6 is not enabled for my containers.

According to https://acme-v01.api.letsencrypt.org/acme/authz/_TEILK55e82bgFlISiQy******WQ my IPv4 address is also tested and I can see Let's encrypt is accessing my web server.

```
{
  "identifier": {
    "type": "dns",
    "value": "sub1.mydomain.com"
  },
  "status": "invalid",
  "expires": "2019-03-29T21:42:19Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "Fetching https://sub1.mydomain.com/.well-known/acme-challenge/lCXWMIDe15t134tbH**********axXb_0: Error getting validation data",
        "status": 400
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_TEILK55e82bgFlISiQyM**********30128176",
      "token": "lCXWMIDe15t134tbH**********axXb_0",
      "validationRecord": [
        {
          "url": "http://sub1.mydomain.com/.well-known/acme-challenge/lCXWMIDe15t134tbH**********axXb_0",
          "hostname": "sub1.mydomain.com",
          "port": "80",
          "addressesResolved": [
            "87.78.*.155",
            "2001:4dd0:af16:5835:****:c4ff:fe14:763d"
          ],
          "addressUsed": "2001:4dd0:af16:5835:****:c4ff:fe14:763d"
        },
        {
          "url": "http://sub1.mydomain.com/.well-known/acme-challenge/lCXWMIDe15t134tbH**********axXb_0",
          "hostname": "sub1.mydomain.com",
          "port": "80",
          "addressesResolved": [
            "87.78.*.155",
            "2001:4dd0:af16:5835:****:c4ff:fe14:763d"
          ],
          "addressUsed": "87.78.*.155"
        },
        {
          "url": "https://sub1.mydomain.com/.well-known/acme-challenge/lCXWMIDe15t134tbH**********axXb_0",
          "hostname": "sub1.mydomain.com",
          "port": "443",
          "addressesResolved": [
            "87.78.*.155",
            "2001:4dd0:af16:5835:****:c4ff:fe14:763d"
          ],
          "addressUsed": "2001:4dd0:af16:5835:****:c4ff:fe14:763d"
        }
      ]
    },
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_TEILK55e82bgFlISiQyM**********30128177",
      "token": "lBsn41hdIOF2Ql7Q6OS-hQqPaB1ImVvsHITyydUFrsc"
    },
    {
      "type": "dns-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_TEILK55e82bgFlISiQyM**********30128178",
      "token": "v31TG5n_RnlrMby_WQQ1tEpptdLhP06wjCT15-kkGtY"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      2
    ],
    [
      1
    ]
  ]
}
```

`docker logs -f nginx`

```
sub1.mydomain.com 64.78.149.164 - - [22/Mar/2019:23:04:03 +0100] "GET /.well-known/acme-challenge/g9lmAk7MD7cTPGRIn***********uYqMlvM HTTP/1.1" 301 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
sub2.mydomain.com 64.78.149.164 - - [22/Mar/2019:23:04:10 +0100] "GET /.well-known/acme-challenge/JIZrajZmaHCsBfApc***********lFFOtVg HTTP/1.1" 301 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
sub3.mydomain.com 64.78.149.164 - - [22/Mar/2019:23:04:17 +0100] "GET /.well-known/acme-challenge/f3_GLNj0e37sDiVk6***********IV__PVU HTTP/1.1" 301 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
sub4.mydomain.com 64.78.149.164 - - [22/Mar/2019:23:04:23 +0100] "GET /.well-known/acme-challenge/7g_w0X5r4cfxbeH8B***********P31JYBA HTTP/1.1" 301 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
sub4.mydomain.com 64.78.149.164 - - [22/Mar/2019:23:04:27 +0100] "GET /.well-known/acme-challenge/twJTB6lg4bokG23RC***********c2bDbnU HTTP/1.1" 301 169 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

So I think I can exclude this issue: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Invalid-authorizations#your-domain-name-advertise-an-aaaa-ipv6-record-but-your-host-or-your-hosts-docker-isnt-actually-reachable-over-ipv6

I can access https://sub1.mydomain.com/.well-known/acme-challenge/test.html without problem via my browser.

I downloaded the `nginx.tmpl` from the master brach again, too.

Does anyone have any idea what is causing my issue or how I can narrow it down?
Thanks

**Comment by CWempe** [comment]
I think I narrowed down the issue:

1. My internet connection is running Dual-Stack (IPv4 and IPv6)
  But the container are only accessible via IPv4 (for now)
2. I have activated forwarding from `http` to `https`
3. Let's Encrypt is trying the following adresses to reach the container
  * `[IPv6 address]:80`
  * `[IPv4 address]:80`
  * `[IPv6 address]:443`

So the one combination of ip address and port (`[IPv4 address]:443`) that would lead to the correct Lets-Encrypt-hash-file is not being tried. :(

But it did work a few weeks ago.
What changed?

I think my two options are:

* disable http-https-forward for `acme-challenge`
* make my reverse proxy IPv6 accessible

**Comment by buchdag** [comment]
Hi.

The third option would be not advertising an AAAA record for domains that won't be publicly reachable through IPv6, as recommended in the doc. But that might not be an option given to you by your ddns provider.

> But it did work a few weeks ago.
> What changed?

LE has an IPv6 to IPv4 fallback mechanism, maybe it worked then and did not work this time.

The fact that `simp_le` does not handle the error correctly isn't helping obviously.

**Comment by buchdag** [comment]
If you want the ACME challenge to happen over http, take a look at #520 and #299

**Comment by CWempe** [comment]
The third option does not work for me, because i need the AAA record for other services.

But the links you provided helped me solve my problem.

I ended up using this patch and everything is fine now. 😃 .
https://gist.github.com/codekitchen/2c519eb7572002afab6a5f979cd42913

Thanks
