### ISSUE TITLE
Cannot reach acme-v01.api.letsencrypt.org

### ISSUE THREAD

**Issue by Deno028** [JrCs/docker-letsencrypt-nginx-proxy-companion#551]
- I got this error recently for new domain.

```
2019/06/13 00:35:28 Running '/app/signal_le_service'
/etc/nginx/certs/example.com /app
Creating/renewal example.com certificates... (example.com)
2019-06-13 00:35:29,749:INFO:simp_le:1382: Generating new account key
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:
...
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4abdd030b8>: Failed to establish a new connection: [Errno -3] Try again',))
```

**Inside the container it only reachs localhost.**

```
docker exec -it nginx-letsencrypt sh
/app # ping acme-v01.api.letsencrypt.org
ping: bad address 'acme-v01.api.letsencrypt.org'
/app # ping google.com
ping: bad address 'google.com'
/app # ping localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.082 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.103 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.080 ms
```

**Comment by Deno028** [comment]
This relates to iptables after I reset everything and turn off iptables settings in docker daemon.js it works normally.

```
/etc/docker/daemon.json 

{
      iptables: false <== remove this line.
}
```
