### ISSUE TITLE
/app/letsencrypt_service: Out of memory

### ISSUE THREAD

**Issue by Chematronix** [JrCs/docker-letsencrypt-nginx-proxy-companion#557]
Hi,

some certs are failing to renew.  I see some (kind of old) errors in the companion's log:

```
Traceback (most recent call last):
  File "/usr/bin/simp_le", line 6, in <module>
    from simp_le import main
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 41, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module
>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_a
side
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3227, in _initia
lize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 623, in add_entr
y
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2017, in find_on
_path
    entries = safe_listdir(path_item)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2076, in safe_li
stdir
    return os.listdir(path)
MemoryError
/app/functions.sh: fork: Out of memory
/app/letsencrypt_service: line 1: /app/letsencrypt_service: Out of memory
/app/letsencrypt_service: line 1: /app/letsencrypt_service: No error information
```

Seems it's a first, search turns out nothing.  Docker has plenty of memory:
```
# free -m
             total       used       free     shared    buffers     cached
Mem:          3955       2454       1501        311         75       1172
-/+ buffers/cache:       1206       2749
```
Running force_renew works.
 
I'd like to trace the cause before I recreate the container.  Any pointers?

My containers:

```
# docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
f2e887d4ffbd        nginx                                    "nginx -g 'daemon of…"   2 months ago        Up 7 weeks                0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
7cc91e025d27        jwilder/docker-gen                       "/usr/local/bin/dock…"   3 months ago        Up 7 weeks                                                           nginx-gen
694794e98a3a        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entr…"   3 months ago        Up 7 weeks                                                           nginx-letsencrypt

```

```
# /usr/bin/simp_le --version
simp_le 0.13.0
```

```
# docker inspect nginx-letsencrypt
[
    {
        "Id": "694794e98a3a493992a733b74e1321e354d7429ea426d1b13dd24ead480573af",
        "Created": "2019-04-05T20:33:05.66496456Z",
        "Path": "/bin/bash",
        "Args": [
            "/app/entrypoint.sh",
            "/bin/bash",
            "/app/start.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 12227,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-05-16T16:50:44.062880868Z",
            "FinishedAt": "2019-05-16T16:50:00.837805494Z"
        },
        "Image": "sha256:7c68d6368c57122d749d3d26a843b2742817bcef43d52c94f419a5489aec88af",
```

**Comment by buchdag** [comment]
Never saw this one. Are you limiting the memory available to the container in any way ?

**Comment by buchdag** [comment]
The only other memory related issue I can remember is this #365

**Comment by Chematronix** [comment]
> Never saw this one. Are you limiting the memory available to the container in any way ?
Nope:

```
# docker stats
CONTAINER ID        NAME                           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
d549be130a00        asdf                 0.00%               212.4MiB / 3.863GiB   5.37%               28.7GB / 3.24GB     1.04GB / 76.7MB     15
f2e887d4ffbd        asdf                          0.00%               3.465MiB / 3.863GiB   0.09%               43.5GB / 44.7GB     2.17GB / 0B         2
cfe8c819de0f        asdf   0.00%               299.2MiB / 3.863GiB   7.56%               621GB / 83GB        16.6GB / 4.09GB     11
a5e8f623ce95        asdf                        0.07%               455.9MiB / 3.863GiB   11.53%              20.7GB / 309GB      281MB / 14.7GB      31
7cc91e025d27        nginx-gen                      0.20%               2.793MiB / 3.863GiB   0.07%               805kB / 0B          3.7GB / 41kB        10
694794e98a3a        nginx-letsencrypt              0.13%               8.414MiB / 3.863GiB   0.21%               849kB / 30kB        3.88GB / 32.8kB     15
```

> The only other memory related issue I can remember is this #365

Hmm... error is different.  I'm going to enable swap just in case.

But even if memory was full at some point, I don't see why it would stop working on the next run... unless there's no next run?

```
# docker exec -ti nginx-letsencrypt ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/bash /app/start.sh
  123 root      2h00 docker-gen -watch -notify /app/signal_le_service -wait 15s
 2973 root      0:00 ps aux
```
letsencrypt_service should be running rite?  So it also died ungracefully and there's no fall back to restart it, perhaps?

**Comment by buchdag** [comment]
Yep, the service should be running.

There is indeed no real process management inside the container. That's planned at some point, but like the rest I can't give any ETA, work on this project being done on my free time.

**Comment by buchdag** [comment]
No activity on this issue for more than 3 months, closing.

**Comment by Ettapp** [comment]
Hi, I had the exact same issue; I use the image for renewing ~10 domains SSL certificates and found the container freezed in the following state while investigating a expired certificate:

```
[above logs lines are normal, and date from one month ago]
/app/letsencrypt_service: line 1: /app/letsencrypt_service: Out of memory
/app/letsencrypt_service: line 1: /app/letsencrypt_service: No error information
```

A `docker ps` command show me that the container is up from my last intervention:

```
[...]
[...] jrcs/letsencrypt-nginx-proxy-companion   Up 3 months
[...]
```

And a `docker stats` shows me:
```
CONTAINER ID        NAME                     CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
[...]
7f51c8fc9555        <my-container-name>      0.24%               4.742MiB / 3.758GiB   0.12%               856kB / 73.5kB      0B / 0B             9
[...]
```

Stopping, removing and running the container again solved the issue, so my dirty-fast-fix (as I sadly cannot take some time to look further for the source of the issue, but would love to and will if still opened the next time I have some free time :slightly_smiling_face: ) was to create a cron task that would restart (stop->remove->run) that container each week...
